# todo -> in progress  GA assignイベントでうつす。
# projectのtodoからin progressに移すaction

name: MoveToInProgress

on:
  issues:
    types: [assigned]

jobs:
  moveToInProgress:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.1.0
        with:
          project: development
          column: 'in progress'
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
